# .cpanel.yml
deployment:
  branch: main
  hooks:
    build: |
      # Installing dependencies
      npm install

      # Build the Vite app for production
      npm run build

    deploy: |
          # Remove existing files in the target directory
          rm -rf /home/njfhditm/portal.crechespots.co.za/*

          # Move the build folder content to the public_html directory
          cp -r dist/* /home/njfhditm/portal.crechespots.co.za/
      
runtime:
  nodejs: '16'  # Specify the Node.js version you need (ensure it's available on cPanel)
