# .cpanel.yml
deployment:
  branch: main
  hooks:
    build: |
      # Installing dependencies
      npm install

      # Build the Vite app for production
      npm run build

    deploy: |
      # Move the build folder content to the public_html directory
      cp -r build/* /home/njfhditm/portal.crechespots.co.za/
      
runtime:
  nodejs: '16'  # Specify the Node.js version you need (ensure it's available on cPanel)
