name: Deploy via SFTP

on:
  push:
    branches:
      - main
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'njfhditm'
          server: '102.212.247.146'
          port: '1624'
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: 'dist/*'
          remote_path: ${{ github.ref == 'refs/heads/main' && '/portal.crechespots.co.za/' || '/demo.crechespots.co.za/' }}